### ISSUE TITLE
Using `vcd-number-with-unit-form-input` withot unitOptions

### ISSUE THREAD

**Issue by ttsvetko** [vmware/vmware-cloud-director-ui-components#105]
Would be great if we have a component which has "Unlimited" option like `vcd-number-with-unit-form-input` but work without passing unitOptions. 

I saw in the template there is a check for `unitOptions` and does not display units if it is an empty array, but the typescript code throws an error.

https://github.com/vmware/vmware-cloud-director-ui-components/blob/master/projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html#L20

**Comment by irahov** [comment]
Fixed in 1.0.0-dev.37
just pass an empty array:
[unitOptions]="[]"
