### ISSUE TITLE
<vcd-form-checkbox> strange behavior when disabled

### ISSUE THREAD

**Issue by georgiatanasov147** [vmware/vmware-cloud-director-ui-components#107]
When the vcd-form-checkbox used as a 'toggle-switch' is in a disabled state, it is still toggle-able. 
Example:
https://stackblitz.com/edit/angular-af3rvr

There is another issue where it can not be reenabled, but I could not reproduce it in stackblitz 😞.  Only in the vcd codebase...

**Comment by ryan-bradford** [comment]
Seems to have been solved at some point down the line, closing this after talking to @georgiatanasov147
