### ISSUE TITLE
vcd-number-with-unit-form-input require validation

### ISSUE THREAD

**Issue by ttsvetanov-vmware** [vmware/vmware-cloud-director-ui-components#128]
When set Validators.required the is no visual indication with message.
When validation massage i too long the number-with-unit-form-input layout is broken. 
[https://onevmw-my.sharepoint.com/:i:/g/personal/ttsvetanov_vmware_com/EROMr7mue4BJumN9ekETrUYBq8fihBdY-wwCZX9KWbXhRw?e=LIWo1A](url)

**Comment by ps37** [comment]
Hey @ttsvetanov-vmware,

What do you mean by "When set Validators.required the is no visual indication with message."?

Are you saying that number-with-unit-form-input with "required" validator is not visibly being shown as required when no input is entered into the field?

**Comment by ttsvetanov-vmware** [comment]
"Are you saying that number-with-unit-form-input with "required" validator is not visibly being shown as required when no input is entered into the field?" - Yes

"Can you please share the link to the Stackblitz that you created?" - I opened with play button in  https://vmware.github.io/vmware-cloud-director-ui-components/numberWithUnitFormInput preview. And after that i added in number-with-unit-form-input.example.component.ts: 
cpuLimit: new FormControl(0, [Validators.required]),
 memory: new FormControl(0, [Validators.required]),

**Comment by irahov** [comment]
Fixed in 1.0.0-dev.37
Required validator is now considered, just do not forget to add also: 
[showAsterisk]="true"
in the template
