### ISSUE TITLE
Datagrid actions buttons move when you select an item

### ISSUE THREAD

**Issue by juanmendes** [vmware/vmware-cloud-director-ui-components#148]
See screenshot
![datagridactions](https://user-images.githubusercontent.com/549331/88699766-c0d4bb80-d0d5-11ea-94b0-8be23761a00a.gif)

Discovered by: bryanv@vmware.com

**Comment by ps37** [comment]
This bug happens when the deprecated ButtonConfig is used to configure action buttons.
This should not be a problem when ActionItem[] is used for the configuration. Verified with bryanv@vmware.com that this is not a bug with the latest way of configuring actions.
