### ISSUE TITLE
Work around for Clarity data grid trackby issue with ActionMenu component

### ISSUE THREAD

**Issue by ps37** [vmware/vmware-cloud-director-ui-components#167]
When there is an [ngForTrackBy] function in the content of <clr-datagrid [(clrDgSelected)]="selection"> on an element other than <clr-dg-row>, the selection logic of the data grid seems to be using that function as the trackBy function for clr-dg-row items. Following is a simple Stackblitz reproducing that error:
https://stackblitz.com/edit/clr-dg-row-trackby-bug

Clarity already has an issue https://github.com/vmware/clarity/issues/3936 on their Github. In the meantime, we need to work around this issue by adding trackBy functionality to the VcdRedItems and VcdRestDgItems directives in the Vcd ui code base.

**Comment by ryan-bradford** [comment]
The workaround for this issue is to wrap your action menu with a template.  This means you should move the action menu to the bottom of the html file in a <ng-template...> and then declare the action menu within the datagrid like this:

```
<clr-dg-action-bar class="top-action-bar" *ngIf="shouldShowActionBarOnTop">
    <!--- We need to instantiate the action bar as its own component to separate its provider chain
    such that the clr-dg-row doesn't get its trackBy. 
    This is due to a bug in Clarity: https://github.com/vmware/clarity/issues/3936 -->
    <ng-container *ngTemplateOutlet="actionBar"> </ng-container>
</clr-dg-action-bar>
```
