### ISSUE TITLE
Allow unit pre-selection in NumberWithUnitFormInputComponent

### ISSUE THREAD

**Issue by bryanvb** [vmware/vmware-cloud-director-ui-components#171]
The NumberWithUnitFormInputComponent allows you to specify which unit you would like the output to be using [inputValueUnit] but does not allow you to pre-select a unit for convenience. For example if I want the control to return MB but I want it to default unit selection to GB I can't do that.

**Comment by irahov** [comment]
Fixed in 1.0.0-dev.37
There is a new input parameter: 
/**
     * The initial display unit.
     * This is useful if you want to prevent finding best match when displaying a value for the first time.
     * For example if you provide 1024 MB and you want it to be displayed as 1024MB instead of 1GB
     */
    @Input() initialValueUnit: Unit;
