### ISSUE TITLE
[ActionMenu] The tooltips on the action menu are being shown even when the text is not too wide

### ISSUE THREAD

**Issue by ps37** [vmware/vmware-cloud-director-ui-components#174]
- The tooltips on the menu are being shown even when the text is not too wide.
This problem is probably because the vcdShowClippedText directive is added to the wrong node

<img width="1657" alt="Screen Shot 2020-08-11 at 8 44 54 AM" src="https://user-images.githubusercontent.com/10735165/89898606-fcc85000-dbae-11ea-8e6f-45e15383cd01.png">

**Comment by ryan-bradford** [comment]
This was fixed somewhere along the line as per @ps37
