### ISSUE TITLE
form-select component error: "Cannot read property 'toString' of null"

### ISSUE THREAD

**Issue by georgiatanasov147** [vmware/vmware-cloud-director-ui-components#196]
When the form select component's 'isReadOnly' input is set to true, and the form group in which the component resides gets reset, the following error occurs: ``` ERROR Error: Cannot read property 'toString' of null```

Stackbliz example:
https://stackblitz.com/edit/angular-ihjgfg?file=src/app/form-select.example.component.ts

**Comment by ryan-bradford** [comment]
The error doesn't appear in version `dev.49`; however, the component still looks strange. Right now, this isn't a use case for anywhere in our app, but we should probably fix this down the line

**Comment by ryan-bradford** [comment]
Closing because this appears to be fixes (https://stackblitz.com/edit/angular-qssv35?file=package.json)
