### ISSUE TITLE
On vcd-datagrid space between action-menu and datagrid is a bit wide

### ISSUE THREAD

**Issue by yumengwu** [vmware/vmware-cloud-director-ui-components#204]
`vcd-action-menu` on `vcd-datagrid` has a css style `height: unset;`, which makes the space between action-menu and datagrid a bit wide. It will be better if it looks like this:

<img width="319" alt="Screen Shot 2020-09-16 at 4 52 06 PM" src="https://user-images.githubusercontent.com/49406822/93391344-02175b00-f83d-11ea-8ece-73a5ec28656e.png">

which has css style `margin-bottom: 10px;`

**Comment by juanmendes** [comment]
This means that the buttons on top of grids on the provider's organization and organization VDCs should look the same.

**Comment by yumengwu** [comment]
This issue is fixed by PR https://github.com/vmware/vmware-cloud-director-ui-components/pull/206
