### ISSUE TITLE
Cannot open vcd-input-with-units examples in Stackblitz

### ISSUE THREAD

**Issue by ttsvetko** [vmware/vmware-cloud-director-ui-components#214]
When i try to run the vcd-input-with-units examples in Stackblitz i see the following error in stackblitz:

Error in /turbo_modules/@angular/compiler@9.1.11/bundles/compiler.umd.js (2845:26)
Can't resolve all parameters for NumberWithUnitFormInputUnitlessExampleComponent: ([object Object], ?).

**Comment by ryan-bradford** [comment]
Updated the Stackbliz template and fixes this issue.
