### ISSUE TITLE
vcd-form-select does not display error icon

### ISSUE THREAD

**Issue by juanmendes** [vmware/vmware-cloud-director-ui-components#251]
When showing an error we need also to show error icon some as vdc-form input
![image](https://user-images.githubusercontent.com/67688226/98809488-4b8fbb00-2426-11eb-9094-a799ae314a28.png)

_Originally posted by @ttsvetanov-vmware in https://github.com/vmware/vmware-cloud-director-ui-components/pull/250#issuecomment-725383949_

**Comment by ryan-bradford** [comment]
Fixed in https://github.com/vmware/vmware-cloud-director-ui-components/pull/262
