### ISSUE TITLE
(impact: medium) Allow vcd-form-select options to be disabled

### ISSUE THREAD

**Issue by juanmendes** [vmware/vmware-cloud-director-ui-components#302]
### Prerequisites

-   [x] Are you running the latest version?
-   [x] Did you perform a basic issue search?

### Description

HTML's option object has a feature where an option is not selectable by the user when you set the [disabled attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attr-disabled).

[`vcd-form-select`](https://vmware.github.io/vmware-cloud-director-ui-components/formSelect/example) takes [`SelectOption`](https://vmware.github.io/vmware-cloud-director-ui-components/compodoc/interfaces/SelectOption.html) objects that don't have a disabled property

### Impact
Users of the library opted to use HTML controls instead of our select abstraction because this feature wasn't available.

Specifically, users wanted the default option empty option (which has placeholder text and an empty value attribute) to be disabled so users cannot select it again in cases where this is a required field

This is a basic property of select's `option`s and should be available.

**Comment by ryan-bradford** [comment]
Fixed by https://github.com/vmware/vmware-cloud-director-ui-components/pull/319
