### ISSUE TITLE
(impact: low) Create a BaseWidgetObject "unwrap self" method.

### ISSUE THREAD

**Issue by georgiatanasov147** [vmware/vmware-cloud-director-ui-components#308]
### Prerequisites

[Check these off before submitting an issue].

-   [x] Are you running the latest version?
-   [x] Did you perform a basic issue search?

For more information, see the `CONTRIBUTING` guide.

### Description

Create a method that returns the current widget's root element object representation.

### Impact

We currently need to do this every time for each widget:

```
export class VcdDatagridWidgetObject<T> extends BaseWidgetObject<T> {
    static tagName = `vcd-datagrid`;

    get vcdDatagrid(): T {
         return this.locatorDriver.unwrap();
    }
}
```

This can be simplified with a simple method in the BaseWidgetObject class, which can then be called whenever needed.

**Comment by juanmendes** [comment]
Could you please update https://github.com/juanmendes/vmware-cloud-director-ui-components/blob/333f2e6506d7227dc6aa20a8eff72c68c6302475/projects/components/src/utils/test/widget-object/angular-widget-object.spec.ts#L76-L78 so it uses the new `self()` instead and delete that `getSelf()` method?
